# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: rrcloudhesive
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: valo-agents
# "service" is the name of this project. This will also be added to your AWS resource names.
service: valo-agents-api

stages:
  default:
    params:
      tableName: "agents-table-${sls:stage}"

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - ssm:GetParameter
          Resource:
            - Fn::GetAtt: [AgentsTable, Arn]
  environment:
    AGENTS_TABLE: ${param:tableName}

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"

resources:
  Resources:
    AgentsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${param:tableName}
